---
title: "Final Project - Evaluation of Clinical Decision Rules for Pediatric Cervical Spine Injuries, Stat 215A, Fall 2021"
author: "Yaxuan Huang, Ishaan Srivastava, and William Torous"
date: "`r format(Sys.time(), '%B %d, %Y')`"
header-includes:
   - \usepackage{float}
   - \usepackage{wrapfig}

output:
  pdf_document:
    number_sections: true
    fig_caption: yes
    
    
bibliography: csi_pecarn.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

The advent of computed tomography (CT) scans has given emergency department (ED) doctors a powerful tool for non-invasive medical imaging. CT scans use repeated X-rays to construct cross-sectional images of a patient's body and provide more information than traditional suites of X-ray images. Because of this information gain, CT scans have become a popular and often standard tool for identifying injuries in adults. The role of CT scans in pediatric care is an active area of research and debate because the procedure delivers 30 times more ionizing radiation to a patient than traditional X-rays (@leonard2011factors). Children are more sensitive to the effects of ionizing radiation because their cells divide more frequently than adults', and it is estimated each CT scan leads to a $x \%$ increase in the rate of fatal cancers for children. These statistics are reported in an average case and can vary with the age of the CT scanner, its calibration for pediatric patients, and the training of the operator in pediatric care [insert citation].

A cervical spine injuries (CSI) refers to an injury in the first seven vertebrae (C1-C7) of the neck. These injuries are extremely important to diagnosis and treat correctly because they can damage the nervous system and lead to paralysis. Common mechanisms of CSI injuries in children include motor vehicle accidents, falls from heights, and sports collisions. CT scans are a standard diagnostic intervention for adults suspected of having a CSI injury. Due to difference in physiology, CSI injuries are less common in children than adults [insert citation] and less than $1 \%$ of pediatric trauma cases in the ED are caused by them (@leonard2011factors). Because of this lower likelihood of injury and children's increased risk from radiation, the decision to use a CT scan must be carefully weighed against alternatives by ED doctors. 

Clinical decision rules are designed to help doctors make more informed judgement calls by summarizing information the medical community has learned from prior patients. The research of @leonard2011factors suggests 8 predictive covariates for when pediatric patients are at greater risk for a CSI; in this report, we use the PCS framework to stress test those covariates. The prevalence of these factors in turn influences whether a patient should receive a CT scan. Additionally we propose additional clinical covariates that contain useful information and build decision rules for ED doctors which summarize this information. A missed CSI diagnosis can have life-altering effects, so having very high sensitivity is a priority for our work. 

# Data

# Exploratory Data Analysis

# References
